<a href="https://colab.research.google.com/github/winnie245/afflita-forex-login-page/blob/main/FLYTA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import pickle

In [ ]:
#Load the data
from google.colab import files
files.upload()

Saving KESUSD=X.csv to KESUSD=X.csv


{'KESUSD=X.csv': b'Date,Open,High,Low,Close,Adj Close,Volume\n2022-06-08,0.008621,0.008644,0.008615,0.008621,0.008621,0\n2022-06-09,0.008619,0.008643,0.008611,0.008619,0.008619,0\n2022-06-10,0.008613,0.008621,0.008595,0.008613,0.008613,0\n2022-06-13,0.008621,0.008637,0.008599,0.008621,0.008621,0\n2022-06-14,0.008602,0.008617,0.008571,0.008602,0.008602,0\n2022-06-15,0.008606,0.008613,0.008595,0.008606,0.008606,0\n2022-06-16,0.008601,0.008613,0.008575,0.008601,0.008601,0\n2022-06-17,0.008590,0.008602,0.008587,0.008590,0.008590,0\n2022-06-20,0.008595,0.008606,0.008570,0.008595,0.008595,0\n2022-06-21,0.008591,0.008595,0.008576,0.008591,0.008591,0\n2022-06-22,0.008576,0.008591,0.008548,0.008576,0.008576,0\n2022-06-23,0.008573,0.008584,0.008565,0.008573,0.008573,0\n2022-06-24,0.008569,0.008595,0.008562,0.008569,0.008569,0\n2022-06-27,0.008565,0.008612,0.008562,0.008565,0.008565,0\n2022-06-28,0.008562,0.008576,0.008558,0.008562,0.008562,0\n2022-06-29,0.008560,0.008580,0.008515,0.008560,0.0085

In [ ]:
#get and show data
#store the data

df = pd.read_csv('KESUSD=X.csv')

#show the data

df

Date      Open      High       Low     Close  Adj Close  Volume
0    2022-06-08  0.008621  0.008644  0.008615  0.008621   0.008621       0
1    2022-06-09  0.008619  0.008643  0.008611  0.008619   0.008619       0
2    2022-06-10  0.008613  0.008621  0.008595  0.008613   0.008613       0
3    2022-06-13  0.008621  0.008637  0.008599  0.008621   0.008621       0
4    2022-06-14  0.008602  0.008617  0.008571  0.008602   0.008602       0
..          ...       ...       ...       ...       ...        ...     ...
257  2023-06-02  0.007265  0.007278  0.007257  0.007378   0.007378       0
258  2023-06-05  0.007257  0.007273  0.007247  0.007257   0.007257       0
259  2023-06-06  0.007259  0.007267  0.007244  0.007259   0.007259       0
260  2023-06-07  0.007249  0.007252  0.007199  0.007249   0.007249       0
261  2023-06-08  0.007193  0.007200  0.007177  0.007188   0.007188       0

[262 rows x 7 columns]

In [ ]:
#creating a variable for predicting 'n' days out into the future,looking 30 days out into the future
projection = 30
#create a new column called prediction
df['Prediction'] = df[['Close']].shift(- projection)
#show the dataset
df



Date      Open      High       Low     Close  Adj Close  Volume  \
0    2022-06-08  0.008621  0.008644  0.008615  0.008621   0.008621       0   
1    2022-06-09  0.008619  0.008643  0.008611  0.008619   0.008619       0   
2    2022-06-10  0.008613  0.008621  0.008595  0.008613   0.008613       0   
3    2022-06-13  0.008621  0.008637  0.008599  0.008621   0.008621       0   
4    2022-06-14  0.008602  0.008617  0.008571  0.008602   0.008602       0   
..          ...       ...       ...       ...       ...        ...     ...   
257  2023-06-02  0.007265  0.007278  0.007257  0.007378   0.007378       0   
258  2023-06-05  0.007257  0.007273  0.007247  0.007257   0.007257       0   
259  2023-06-06  0.007259  0.007267  0.007244  0.007259   0.007259       0   
260  2023-06-07  0.007249  0.007252  0.007199  0.007249   0.007249       0   
261  2023-06-08  0.007193  0.007200  0.007177  0.007188   0.007188       0   

     Prediction  
0      0.008507  
1      0.008507  
2      0.008507  
3      0.008500  
4      0.008498  
..          ...  
257         NaN  
258         NaN  
259         NaN  
260         NaN  
261         NaN  

[262 rows x 8 columns]

In [ ]:
from os import X_OK
#create the independent dataset (x)
x = np.array(df[['Close']])
#remove the last 30 days
x = x[:-projection]
print(x)

[[0.008621]
 [0.008619]
 [0.008613]
 [0.008621]
 [0.008602]
 [0.008606]
 [0.008601]
 [0.00859 ]
 [0.008595]
 [0.008591]
 [0.008576]
 [0.008573]
 [0.008569]
 [0.008565]
 [0.008562]
 [0.00856 ]
 [0.008562]
 [0.008556]
 [0.008554]
 [0.008552]
 [0.008547]
 [0.008543]
 [0.00854 ]
 [0.00854 ]
 [0.008524]
 [0.008536]
 [0.008532]
 [0.008532]
 [0.008529]
 [0.008518]
 [0.008507]
 [0.008507]
 [0.008507]
 [0.0085  ]
 [0.008498]
 [0.008503]
 [0.008485]
 [0.008483]
 [0.008482]
 [0.008475]
 [0.008471]
 [0.008464]
 [0.00846 ]
 [0.008467]
 [0.008396]
 [0.008389]
 [0.00845 ]
 [0.008446]
 [0.008442]
 [0.008439]
 [0.008435]
 [0.008432]
 [0.008428]
 [0.008425]
 [0.008414]
 [0.00841 ]
 [0.008407]
 [0.008403]
 [0.00841 ]
 [0.0084  ]
 [0.008337]
 [0.008393]
 [0.008389]
 [0.008393]
 [0.008319]
 [0.008379]
 [0.008316]
 [0.008316]
 [0.008382]
 [0.008372]
 [0.008372]
 [0.008375]
 [0.008306]
 [0.008375]
 [0.008302]
 [0.008361]
 [0.008361]
 [0.008295]
 [0.008368]
 [0.008295]
 [0.008351]
 [0.008288]
 [0.008347]
 [0.

In [ ]:
#create the dependent dataset (y)
y = df['Prediction'].values
y = y[:-projection]
print(y)


[0.008507 0.008507 0.008507 0.0085   0.008498 0.008503 0.008485 0.008483
 0.008482 0.008475 0.008471 0.008464 0.00846  0.008467 0.008396 0.008389
 0.00845  0.008446 0.008442 0.008439 0.008435 0.008432 0.008428 0.008425
 0.008414 0.00841  0.008407 0.008403 0.00841  0.0084   0.008337 0.008393
 0.008389 0.008393 0.008319 0.008379 0.008316 0.008316 0.008382 0.008372
 0.008372 0.008375 0.008306 0.008375 0.008302 0.008361 0.008361 0.008295
 0.008368 0.008295 0.008351 0.008288 0.008347 0.008351 0.008282 0.008344
 0.008311 0.00834  0.008344 0.00834  0.008282 0.008333 0.00833  0.008333
 0.008326 0.008326 0.008323 0.008306 0.008319 0.008258 0.008258 0.008251
 0.008309 0.008306 0.008244 0.008302 0.008299 0.008295 0.008434 0.008292
 0.008282 0.008278 0.008275 0.008369 0.008268 0.008264 0.008261 0.008258
 0.008254 0.008251 0.008247 0.008244 0.008247 0.008244 0.008234 0.00823
 0.008227 0.008224 0.008234 0.008217 0.008214 0.00821  0.008207 0.00823
 0.008215 0.0082   0.008197 0.008193 0.008193 0.00819

In [ ]:
#split the datasets into 85% training and 15% testing datasets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = .15)

In [ ]:
#create and train the model
linReg = LinearRegression()
#Train the model
linReg.fit(x_train, y_train)

LinearRegression()

In [ ]:
#Testing the model using score
linReg_confidence = linReg.score(x_test, y_test)
print('Linear Regression Confidence:',linReg_confidence)

Linear Regression Confidence: 0.9380484752884077


In [ ]:
#creating a variable called x_projection and set it to be equal to the last 30 raws of data from the oriinal price
x_projection = np.array(df[['Close']])[-projection:]
print(x_projection)

[[0.007364]
 [0.007407]
 [0.007358]
 [0.00735 ]
 [0.007388]
 [0.007386]
 [0.007383]
 [0.00738 ]
 [0.007369]
 [0.007321]
 [0.00731 ]
 [0.007353]
 [0.007348]
 [0.007342]
 [0.007331]
 [0.007323]
 [0.007326]
 [0.00731 ]
 [0.007252]
 [0.007286]
 [0.007239]
 [0.007281]
 [0.007275]
 [0.007273]
 [0.007265]
 [0.007378]
 [0.007257]
 [0.007259]
 [0.007249]
 [0.007188]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#print linear regression model's predictions for the next 30 days
linReg_prediction = linReg.predict(x_projection)
print(linReg_prediction)

[0.00702216 0.00707451 0.00701485 0.00700511 0.00705137 0.00704894
 0.00704529 0.00704164 0.00702824 0.00696981 0.00695642 0.00700877
 0.00700268 0.00699537 0.00698198 0.00697224 0.0069759  0.00695642
 0.00688581 0.0069272  0.00686998 0.00692111 0.00691381 0.00691137
 0.00690163 0.0070392  0.0068919  0.00689433 0.00688216 0.00680789]


In [ ]:
filename= 'forex_pred_model'
pickle.dump(linReg,open(filename,'wb'))

In [ ]:
loaded_linReg = pickle.load(open(filename,'rb'))
loaded_linReg.predict(x_projection)

array([0.00702216, 0.00707451, 0.00701485, 0.00700511, 0.00705137,
       0.00704894, 0.00704529, 0.00704164, 0.00702824, 0.00696981,
       0.00695642, 0.00700877, 0.00700268, 0.00699537, 0.00698198,
       0.00697224, 0.0069759 , 0.00695642, 0.00688581, 0.0069272 ,
       0.00686998, 0.00692111, 0.00691381, 0.00691137, 0.00690163,
       0.0070392 , 0.0068919 , 0.00689433, 0.00688216, 0.00680789])